# Generated by Django 4.2 on 2024-06-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ciutat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('temporada', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partit', models.DateTimeField()),
                ('gols_local', models.IntegerField(default=0)),
                ('gols_visitant', models.IntegerField(default=0)),
                ('equip_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partits_local', to='lliga.equip')),
                ('equip_visitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partits_visitant', to='lliga.equip')),
                ('lliga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partits', to='lliga.lliga')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('edat', models.IntegerField()),
                ('posicio', models.CharField(max_length=50)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadors', to='lliga.equip')),
            ],
        ),
        migrations.AddField(
            model_name='equip',
            name='lliga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='lliga.lliga'),
        ),
    ]
